#
# Makefile for development of game using Dragonfly
#
# 'make' to build executable
# 'make depend' to generate new dependency list
# 'make clean' to remove all constructed files
#
# Variables of interest:
#   GAMESRC is the source code files for the game being developed
#   GAME is the game main() source
#   DEBUG can be set to -DDEBUG to enable various debug flags
#

CC= g++ 
PLATFORM= -DCYGWIN		# uncomment for cygwin
#PLATFORM= -DMACOS  		# uncomment for macos
LDFLAGS= -lncurses -lrt	# uncomment linux/cygwin
#LDFLAGS= -lncurses 		# uncomment for macos
ENGPATH= Dragonfly_Engine
GAMEENG= Manager.cpp LogManager.cpp Utility.cpp Clock.cpp GameManager.cpp \
		Position.cpp Object.cpp ObjectList.cpp ObjectListIterator.cpp Event.cpp \
		EventStep.cpp WorldManager.cpp GraphicsManager.cpp InputManager.cpp \
		EventKeyboard.cpp EventMouse.cpp EventCollision.cpp EventOut.cpp \
		Frame.cpp Sprite.cpp ResourceManager.cpp Box.cpp ViewObject.cpp \
		EventView.cpp SceneGraph.cpp
GAMESRC= Character.cpp EventRefresh.cpp Hero.cpp Star.cpp
GAME= game.cpp
EXECUTABLE= game
OBJECTS= $(addprefix $(ENGPATH)/, $(GAMEENG:.cpp=.o)) $(GAMESRC:.cpp=.o)
VPATH= $(ENGPATH)

all: $(EXECUTABLE) Makefile

$(EXECUTABLE): $(OBJECTS) $(GAME) $(GAMEENG)
	$(CC) $(GAME) $(OBJECTS) $(LDFLAGS) -I$(ENGPATH) -o $@

.cpp.o: 
	$(CC) -c $(DEBUG) -I$(ENGPATH) $< -o $@

clean:
	rm -rf $(OBJECTS) $(EXECUTABLE) core log.txt Makefile.bak *~

depend: 
	makedepend *.cpp $(ENGPATH)/*.cpp 2> /dev/null

# DO NOT DELETE
